---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: orders
data:
  url: "amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJz"
  username: "b3JkZXJzX3VzZXI="
  password: "ZGVmYXVsdF9wYXNzd29yZA=="